// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheImageLogo: typeof import('./components/TheImageLogo.vue')['default']
    TheLogo: typeof import('./components/TheLogo.vue')['default']
    ThePointsLogo: typeof import('./components/ThePointsLogo.vue')['default']
    TheVortex: typeof import('./components/TheVortex.vue')['default']
  }
}

export {}
